name       : ptyprocess
version    : 0.7.0
release    : 10
source     :
    - https://pypi.python.org/packages/source/p/ptyprocess/ptyprocess-0.7.0.tar.gz : 5c5d0a3b48ceee0b48485e0c26037c0acd7d29765ca3fbb5cb3831d347423220
homepage   : https://github.com/pexpect/ptyprocess
license    : ISC
component  : programming.python
summary    : Python pseudo-terminal module
description: |
    Launch a subprocess in a pseudo terminal (pty), and interact with both the process and its pty.
builddeps  :
    - python2-pytest # check
    - python-pytest  # check
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
