name       : ptyprocess
version    : 0.5.2
release    : 3
source     :
    - https://pypi.python.org/packages/51/83/5d07dc35534640b06f9d9f1a1d2bc2513fb9cc7595a1b0e28ae5477056ce/ptyprocess-0.5.2.tar.gz : e64193f0047ad603b71f202332ab5527c5e52aa7c8b609704fc28c0dc20c4365
license    : ISC
component  : programming.python
summary    : Python pseudo-terminal module
description: |
    Launch a subprocess in a pseudo terminal (pty), and interact with both the process and its pty.
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
