name       : ptyprocess
version    : 0.5.1
release    : 1
source     :
    - https://pypi.python.org/packages/db/d7/b465161910f3d1cef593c5e002bff67e0384898f597f1a7fdc8db4c02bf6/ptyprocess-0.5.1.tar.gz : 0530ce63a9295bfae7bd06edc02b6aa935619f486f0f1dc0972f516265ee81a6
license    : ISC 
component  : programming.python 
summary    : Python pseudo-terminal module 
description: |
    Launch a subprocess in a pseudo terminal (pty), and interact with both the process and its pty.
setup      : |
    %python_setup
install    : |
    %python_install
