name       : ptyprocess
version    : 0.6.0
release    : 8
source     :
    - https://pypi.python.org/packages/source/p/ptyprocess/ptyprocess-0.6.0.tar.gz : 923f299cc5ad920c68f2bc0bc98b75b9f838b93b599941a6b63ddbc2476394c0
license    : ISC
component  : programming.python
summary    : Python pseudo-terminal module
description: |
    Launch a subprocess in a pseudo terminal (pty), and interact with both the process and its pty.
builddeps  :
    - python2-pytest # check
    - python-pytest # check
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
